# Makefile for the RetroBrew SBC-386 relocatable BIOS
#  Use Open Watcom WMAKE to make (or NMAKE?)
#  Use Open Watcom C 1.9
#   or NASM version 2.08 (cwsdpmi needed, or WINNT)
#       NASM ver. 2.09 is reported to have problems
#
#
ROM = 64
CHIP = 64

# Set CRC option:  0, 1, 2, 16
CRC = 16
CRC_AT = 0xFFEE
BIN = __FOO__

CC = wcl -c
#COPT = /Gs2 /Zp1 /Ois /DSBC188=1 /Fl
# Open Watcom C Compiler options:
# -bt=DOS  build target
# -mc   compact memory model  -f
# -zdp  DS == DGROUP
# -zu   SS != DGROUP
# -s    remove stack overflow checks
# -zp1  set struct packing alignment to 1
# -oi   inline intrinsic functions
# -os   optimize for space
# -1    generate code for 186 or higher
# -3    generate code for 386 or higher
# -fpi87 use 8087 instructions
# -q	quiet compile
COPT = -q -mc -zdp -zu -s -zp1 -oi -os -3 -fpi87 -DSBC386=1
CLIST = wdis -l -s $*
SIZE = -DROM=$(ROM) -DCHIP=$(CHIP) $(RED)
#
# The newer version of NASM provides the __DATE__ & __TIME__ 
#NASM = nasm
NASM = c:\nasm-208\nasm  
ASM = $(NASM) -fobj
#
#NOPT = $(RED) $(FAST) -O9 $(TRC) $(ANSI) $(TESTS)
NOPT = -O9 -dROM=$(ROM)
#LINK = wcl
LINK = wlink
# Open Watcom liner options:
# -lr   create a DOS real-mode program
#LOPT = -lr -q
LOPT =



# Watcom tools

RM=rm -f
EXE2ROM=..\tools\exe2rom.exe
HEX2BIN=..\tools\hex2bin.exe
BIN2HEX=..\tools\bin2hex.exe
COPT18=..\tools\copt.exe
CP=copy
CAT=copy/b
PLUS=+


H2INC = -c@ -b9

INCLUDES = seg_def.inc i386EX.inc macro.inc bda.inc date.inc
CINCL = cprintf.h sbc188.h

OBJECTS = start.obj cprintf.obj signon.obj muldiv.obj uart_det.obj crc16.obj \
	stub.obj


.EXTENSIONS:
.EXTENSIONS: .bin .obj .exe .asm .c .h .tmp

.asm.bin:
	$(NASM) $(NOPT) -f bin -o $@ -l $*.lst  $*.asm
.asm.obj:
	$(ASM) $(NOPT) -o $@ -l $*.lst  $*.asm
.c.obj:
	$(CC) $(COPT) -fo=$@ $*.c
	$(CLIST)

all:	rom064.hex rom128.hex rom256.hex rom512.hex    0rom128.hex
	$(RM) $(BIN)

# do the following since "0rom..." is easier to find when burning ROM chip
0rom128.hex:	rom128.hex
	$(CP) rom128.hex 0rom128.HEX



start.exe:	$(OBJECTS)
	WLINK @start.lkk
bda.inc:	bda.h bda.rul
	$(COPT18) $(H2INC) -f $*.h -o $*.inc bda.rul
bda.obj:	bda.inc
	$(NASM) -fobj -O1+ -dXXX -lbda.lst -obda.obj bda.inc
boot.tmp:	boot.asm $(INCLUDES)
        $(NASM) -fbin $(NOPT) -dROM=$(ROM) -o$*.tmp -l$*.lst  $*.asm
rom064.hex:	start.exe boot.tmp
	$(EXE2ROM) -v -s boot.tmp -r $(ROM) -e $(CHIP) start.exe $(BIN)
	$(BIN2HEX) -c$(CRC)=$(CRC_AT) -R $(CHIP)K $(BIN) -o rom064.hex

rom128.hex:	rom064.hex
	$(HEX2BIN) -R128k -o$(BIN) -d64K $**
	$(BIN2HEX) -R128k -o$@ $(BIN)
rom256.hex:	rom064.hex
	$(HEX2BIN) -R256k -o$(BIN) -d192K $**
	$(BIN2HEX) -R256k -o$@ $(BIN)
rom512.hex:	rom064.hex
	$(HEX2BIN) -R512k -o$(BIN) -d448K $**
	$(BIN2HEX) -R512k -o$@ $(BIN)

start.obj:	start.asm  $(INCLUDES) boot.asm
	$(ASM) $(NOPT) -o$@ -l$*.lst -dCRC=$(CRC) -dCRC_AT=$(CRC_AT) $*.asm
crc16.obj:	crc.asm $(INCLUDES) crc16tab.inc
	$(ASM) $(NOPT) -o$@ -lcrc16.lst -dCRC16=1  crc.asm

## obsolete -- from TEST1 
startup.hex:    startup.asm $(INCLUDE) $(ASM_INC)
        $(NASM) -fith $(NOPT) -dCRC=$(CRC) -dROM=$(ROM_START) -o$*.hex -l$*.lst  $*.asm

# copy of 1985 PC/AT bios data area 
dseg:	dseg.asm	.SYMBOLIC
	masm /X dseg.asm,nul,dseg.lst;



# Maintenance

tidy:	.SYMBOLIC
	$(RM) *.lst
	$(RM) *.map
	$(RM) *.err
	$(RM) $(BIN)

clean:	tidy .SYMBOLIC
	$(RM) *.tmp
	$(RM) *.obj
	$(RM) *.exe

spotless: clean .SYMBOLIC
	$(RM) *.lib
	$(RM) *.bak
	$(RM) *.bk?
	$(RM) foo*
	$(RM) goo*
	$(RM) foo*.*
	$(RM) goo*.*

# Dependencies
foo.obj:	foo.c
uart_det.obj:	uart_det.asm	$(INCLUDES)
muldiv.obj:	muldiv.asm	$(INCLUDES)
stub.obj:	stub.asm	$(INCLUDES)

signon.obj:	signon.c $(CINCL)
cprintf.obj:    cprintf.c sbc188.h





#########################################################################
# Leftovers from SBC188

sio.obj:	sio.c sbc188.h sio.h
nvram.obj:      nvram.c sbc188.h ds1302.h sio.h equates.h ide.h bda.inc sdcard.h libc.h
libc.obj:	libc.c
debug.obj:      debug.c mytypes.h equates.h sio.h debug.h bda.inc
kbd.obj:	kbd.c mytypes.h sbc188.h equates.h kbd_pc.h kbd_stat.h config.asm
m8563lib.obj:	m8563lib.c mytypes.h sbc188.h equates.h m8563inc.h ega9a.h
vga3lib.obj:	vga3lib.c mytypes.h sbc188.h equates.h vga3inc.h v3std.h v3_par1.h vga_def.h
fdc8272.obj:	fdc8272.c mytypes.h sbc188.h io.h fdc8272.h wd37c65.h
wd37c65.obj:	wd37c65.c mytypes.h sbc188.h io.h wd37c65.h

dprintf.obj:	dprintf.c sbc188.h

font2.obj:	font2.c font_vga.h
font2.exe:	font2.obj
	$(LINK) $(LOPT) -k1024 -fe=$@ -fm=$*.map $<
font2.bin:	font2.exe
	$(EXE2ROM) font2.exe font2.bin -s NUL -r 32K -e 32K
font2.hex:	font2.bin
	$(BIN2HEX) -o font2.hex -S 4k font2.bin
font2a.bin:	font2.hex
	$(HEX2BIN) -R 4K -o font2a.bin font2.hex


#########################################################################

