# Makefile for the RetroBrew SBC-386 relocatable BIOS
#  Use Open Watcom C 1.9
#  Use NASM version 2.08 (cwsdpmi needed, or WINNT)
#       NASM ver. 2.09 is reported to have problems
#  Use Open Watcom NMAKE to make
#
#
FAST = -DHAS_FASTCALL=1

# Set FPU to 1 if Math Co-processor is present
FPU = 1

ROM_SEG = 0xF000
ROM_START = 0x0000
ROM512 = 0x70000
ROM256 = 0x30000
ROM128 = 0x10000
ROM064 = 0x00000

# Set CRC option:  0, 1, 2, 16
CRC = 16
CRC_AT = 0xFFEE
BIN = __FOO__

CC = wcl -c
#COPT = /Gs2 /Zp1 /Ois /DSBC188=1 /Fl
# Open Watcom C Compiler options:
# -mc   compact memory model -f
# -zdp  DS == DGROUP
# -zu   SS != DGROUP
# -s    remove stack overflow checks
# -zp1  set struct packing alignment to 1
# -oi   inline intrinsic functions
# -os   optimize for space
# -1    generate code for 186 or higher
# -fpi87 use 8087 instructions
# -q	quiet compile
COPT = -q -mc -zdp -zu -s -zp1 -oi -os -1 -fpi87 -DSBC386=1
CLIST = wdis -l -s $*
CINCL = -I$(WATCOM)\H
SIZE = -DROM=$(ROM) -DCHIP=$(CHIP) $(RED)
#
# The newer version of NASM provides the __DATE__ & __TIME__ 
#NASM = nasm
NASM = nasm208
#
CRCDEFS = -dCRC=$(CRC) -dCRC_AT=$(CRC_AT)
NOPT = $(FAST) $(CRCDEFS) -dROM_SEG=$(ROM_SEG) -dFPU=$(FPU) -O9+
LINK = wcl
# Open Watcom linker options:
# -lr   create a DOS real-mode program
#LOPT = -mc -lr
LOPT = -lr -q

!ifdef __UNIX__
RM=rm -f
EXE2ROM=tools/exe2rom
HEX2BIN=tools/hex2bin.exe
BIN2HEX=tools/bin2hex.exe
CP=cp
CAT=cat
PLUS=
!else
RM=rm -f
;RM=del -q
EXE2ROM=..\tools\exe2rom.exe
HEX2BIN=..\tools\hex2bin.exe
BIN2HEX=..\tools\bin2hex.exe
CP=copy
CAT=copy/b
PLUS=+
LISTDIR=F:\
!endif


INCLUDE = i386ex.inc macro.inc crc16tab.inc
ASM_INC = ds1302.asm pm_sio.asm pm_test.asm rm_test.asm


all:    tcrc.obj \
	startup.hex rom064.hex rom128.hex rom256.hex rom512.hex  0rom128.hex

tcrc.obj:	tcrc.c crc16tab.inc
	$(CC) $(COPT) $(CINCL) $*.c
	$(CLIST)


startup.bin:    startup.asm $(INCLUDE) $(ASM_INC)
        $(NASM) -fbin $(NOPT) -o$*.bin -l$*.lst  $*.asm

startup.hex:    startup.asm $(INCLUDE) $(ASM_INC)
        $(NASM) -fith $(NOPT) -dCRC=$(CRC) -dROM=$(ROM_START) -o$*.hex -l$*.lst  $*.asm

$(BIN):	startup.hex
        $(HEX2BIN) -c$(CRC)=$(CRC_AT) -R64k -o $(BIN) -s$(ROM_START) -d$(ROM064)  startup.hex

rom064.hex:	$(BIN)
        $(BIN2HEX) -R64k -o $@  $(BIN)

rom128.hex:     $(BIN)
        $(BIN2HEX) -R128k -o $@  -d$(ROM128) $(BIN)

0rom128.hex:	rom128.hex
	$(CP) *.lst  $(LISTDIR)
	$(CP) rom128.hex 0rom128.hex

rom256.hex:     startup.hex
        $(BIN2HEX) -R256k -o $@  -d$(ROM256) $(BIN)

rom512.hex:     startup.hex
        $(BIN2HEX) -R512k -o $@  -d$(ROM512) $(BIN)
#        $(RM) $(BIN)



tidy:
	$(RM) $(BIN)
        $(RM) *.lst

clean:  tidy
	$(RM) *.obj
        $(RM) *.hex
